[package]
name = "ame-models"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true
